package oop_uas;

import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static oop_uas.koneksi.getConnection;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Taa
 */
public class frmtodolist extends javax.swing.JFrame {
    DefaultTableModel tm = new DefaultTableModel();
    /**
     * Creates new form frmtodolist
     */
    public frmtodolist() throws SQLException {
        initComponents();
        jtb.setModel(tm);
        tm.addColumn("ID");
        tm.addColumn("Task Name");
        tm.addColumn("Description");
        tm.addColumn("Date");
        tm.addColumn("Category");
        list_all();
        
    }

    private void list_all() throws SQLException{
        Connection cnn = getConnection();
        tm.getDataVector().removeAllElements();
        tm.fireTableDataChanged();
        
        if(cnn.isClosed()){
            System.out.println("Koneksi Tertutup");
        }else{
            String sql = "Select * from todo order by id;";
            PreparedStatement ps = cnn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()){
                Object[] dta = new Object[5];
                dta[0] = rs.getString("id");
                dta[1] = rs.getString("name");
                dta[2] = rs.getString("description");
                dta[3] = rs.getString("date");
                dta[4] = rs.getString("category");
                tm.addRow(dta);
            }
            cnn.close();
        }
    }
    
    private void StoreData() throws SQLException{
        Connection cnn = getConnection();
        String NM = txtNAME.getText();
        String DS = txtDESCRIPTION.getText();
        String DT = txtDATE.getText();
        String CT = txtCATEGORY.getText();
        if (!cnn.isClosed()){
            PreparedStatement ps = cnn.prepareStatement("INSERT INTO todo(name, description, date, category) VALUES (?,?,?,?)");   
            ps.setString(1, NM);
            ps.setString(2, DS);
            ps.setString(3, DT);
            ps.setString(4, CT);
            ps.executeUpdate();
    }
    }
    
      private void UpdateData() throws SQLException{
        String sql = "UPDATE todo SET name=?, description=?, date=?, category=? WHERE id=?";
    
    try (Connection cnn = getConnection(); 
         PreparedStatement ps = cnn.prepareStatement(sql)) {
        
        if (!cnn.isClosed()) {
            String ID = LBNAME.getText(); 
            String NM = txtNAME.getText();
            String DS = txtDESCRIPTION.getText();
            String DT = txtDATE.getText();
            String CT = txtCATEGORY.getText();
            
            ps.setString(1, NM);
            ps.setString(2, DS);
            ps.setString(3, DT);
            ps.setString(4, CT);
            ps.setString(5, ID);
            ps.executeUpdate();
            
            txtNAME.setText("");
            txtDESCRIPTION.setText("");
            txtDATE.setText("");
            txtCATEGORY.setText("");
            LBNAME.setText("");
}
}
    }
    private void DestroyData() throws SQLException{
        Connection cnn = getConnection();
        if(!cnn.isClosed()){
            PreparedStatement ps = cnn.prepareStatement("DELETE FROM todo WHERE id=?;");

        ps.setString(1, LBNAME.getText());
        ps.executeUpdate();
        cnn.close();
}
}
    
private void loadphoto (String idteman){
    String pas0 = "img/pas0.png";
    String pas = "img/pas"+ idteman+".png";
    
    BufferedImage bimg = loadIMG.loadImage(pas);
    if (bimg == null){
        bimg = loadIMG.loadImage(pas0);
    }
    ImageIcon iconimg = new ImageIcon(bimg);
    pasphoto1.setIcon(iconimg);
    pasphoto2.setIcon(iconimg);
    pasphoto3.setIcon(iconimg);
    pasphoto4.setIcon(iconimg);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb = new javax.swing.JTable();
        pasphoto = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        txtNAME = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDESCRIPTION = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDATE = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCATEGORY = new javax.swing.JTextField();
        cmdBARU = new javax.swing.JButton();
        cmdUBAH = new javax.swing.JButton();
        cmdHAPUS = new javax.swing.JButton();
        cmdTUTUP = new javax.swing.JButton();
        pasphoto1 = new javax.swing.JLabel();
        pasphoto2 = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LBNAME = new javax.swing.JLabel();
        pasphoto3 = new javax.swing.JLabel();
        pasphoto4 = new javax.swing.JLabel();

        panel1.setBackground(new java.awt.Color(255, 220, 232));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 0, 36)); // NOI18N
        jLabel7.setText("Login");

        jLabel8.setFont(new java.awt.Font("Informal Roman", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 102));
        jLabel8.setText("Taskaroo");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(60, 60, 60)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 231, 252));

        jtb.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N
        jtb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtb);

        pasphoto.setBackground(new java.awt.Color(255, 242, 255));

        jLabel2.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N
        jLabel2.setText("Name");

        txtNAME.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N
        txtNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNAMEActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N
        jLabel3.setText("Description");

        txtDESCRIPTION.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N
        jLabel4.setText("Date");

        txtDATE.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N
        jLabel6.setText("Category (work/personal/urgent)");

        txtCATEGORY.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N

        cmdBARU.setBackground(new java.awt.Color(183, 207, 255));
        cmdBARU.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N
        cmdBARU.setText("Add");
        cmdBARU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBARUActionPerformed(evt);
            }
        });

        cmdUBAH.setBackground(new java.awt.Color(222, 255, 217));
        cmdUBAH.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N
        cmdUBAH.setText("Edit");
        cmdUBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUBAHActionPerformed(evt);
            }
        });

        cmdHAPUS.setBackground(new java.awt.Color(255, 255, 153));
        cmdHAPUS.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N
        cmdHAPUS.setText("Delete");
        cmdHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHAPUSActionPerformed(evt);
            }
        });

        cmdTUTUP.setBackground(new java.awt.Color(255, 165, 165));
        cmdTUTUP.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N
        cmdTUTUP.setText("Cancel");
        cmdTUTUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTUTUPActionPerformed(evt);
            }
        });

        panel2.setBackground(new java.awt.Color(255, 220, 232));

        jLabel9.setFont(new java.awt.Font("Sitka Text", 0, 36)); // NOI18N
        jLabel9.setText("To Do List");

        jLabel10.setFont(new java.awt.Font("Informal Roman", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 102));
        jLabel10.setText("Taskaroo");

        jLabel5.setFont(new java.awt.Font("Perpetua", 0, 12)); // NOI18N
        jLabel5.setText("ID :");

        LBNAME.setFont(new java.awt.Font("Perpetua", 0, 12)); // NOI18N
        LBNAME.setText("...");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(132, 132, 132)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LBNAME)
                .addGap(228, 228, 228))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(LBNAME)))))
        );

        javax.swing.GroupLayout pasphotoLayout = new javax.swing.GroupLayout(pasphoto);
        pasphoto.setLayout(pasphotoLayout);
        pasphotoLayout.setHorizontalGroup(
            pasphotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pasphotoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pasphotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDESCRIPTION)
                    .addComponent(txtNAME, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pasphotoLayout.createSequentialGroup()
                        .addGroup(pasphotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(txtDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdTUTUP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(pasphotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pasphotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCATEGORY))
                            .addGroup(pasphotoLayout.createSequentialGroup()
                                .addComponent(pasphoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pasphoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmdBARU))))
                    .addGroup(pasphotoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(43, 43, 43)
                        .addComponent(pasphoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdHAPUS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdUBAH)))
                .addGap(18, 18, 18))
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pasphotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pasphotoLayout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(pasphoto4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(404, Short.MAX_VALUE)))
        );
        pasphotoLayout.setVerticalGroup(
            pasphotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pasphotoLayout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pasphotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pasphotoLayout.createSequentialGroup()
                        .addGroup(pasphotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmdUBAH)
                            .addComponent(cmdHAPUS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(pasphoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addComponent(txtDESCRIPTION, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pasphotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pasphotoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pasphotoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCATEGORY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pasphotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pasphotoLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(pasphotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmdBARU)
                                    .addComponent(cmdTUTUP)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pasphotoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pasphotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pasphoto1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pasphotoLayout.createSequentialGroup()
                                        .addComponent(pasphoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)))))))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(pasphotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pasphotoLayout.createSequentialGroup()
                    .addContainerGap(311, Short.MAX_VALUE)
                    .addComponent(pasphoto4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(46, 46, 46)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pasphoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pasphoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNAMEActionPerformed

    private void cmdTUTUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTUTUPActionPerformed
        if (cmdTUTUP.getText().equals("Close")){
            int jtp = JOptionPane.showOptionDialog(this, "Close the form?", "Confirm Close Form", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if(jtp == JOptionPane.YES_OPTION){
            dispose();    
        }
        }else{
            cmdTUTUP.setText("Close");
            cmdBARU.setText("Add");
            cmdHAPUS.setEnabled(true);
            cmdUBAH.setEnabled(true);
            cmdBARU.setEnabled(true);
        }
    }//GEN-LAST:event_cmdTUTUPActionPerformed

    private void jtbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbMouseClicked
        LBNAME.setText(jtb.getValueAt(jtb.getSelectedRow(), 0).toString());
        txtNAME.setText(jtb.getValueAt(jtb.getSelectedRow(), 1).toString());
        txtDESCRIPTION.setText(jtb.getValueAt(jtb.getSelectedRow(), 2).toString());
        txtDATE.setText(jtb.getValueAt(jtb.getSelectedRow(), 3).toString());
        txtCATEGORY.setText(jtb.getValueAt(jtb.getSelectedRow(), 4).toString());
        loadphoto(LBNAME.getText());
    }//GEN-LAST:event_jtbMouseClicked

    private void cmdBARUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBARUActionPerformed
        if (cmdBARU.getText().equals("Add")){
            cmdBARU.setText("Save");
            cmdTUTUP.setText("Cancel");
            cmdUBAH.setEnabled(false);
            cmdHAPUS.setEnabled(false);
            
            txtNAME.setText("");
            txtDESCRIPTION.setText("");
            txtDATE.setText("");
            txtCATEGORY.setText("");
        }else{
            try {
                StoreData();
                list_all();
            } catch (SQLException ex) {
                Logger.getLogger(frmtodolist.class.getName()).log(Level.SEVERE, null, ex);
            }
            cmdBARU.setText("Add");
            cmdTUTUP.setText("Close");
            cmdUBAH.setEnabled(true);
            cmdHAPUS.setEnabled(true);
        }
    }//GEN-LAST:event_cmdBARUActionPerformed

    private void cmdHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHAPUSActionPerformed
        try {
    int jtp = JOptionPane.showOptionDialog(this, 
            "Are you sure you want to delete " + txtNAME.getText() + "?", 
            "Confirm Delete", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.ERROR_MESSAGE, 
            null, 
            null, 
            null);
    if (jtp == JOptionPane.YES_OPTION) {
        DestroyData();
        list_all();
    }
} catch (SQLException ex) {
    Logger.getLogger(frmtodolist.class.getName()).log(Level.SEVERE, null, ex);
}
    }//GEN-LAST:event_cmdHAPUSActionPerformed

    private void cmdUBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUBAHActionPerformed
         if (cmdUBAH.getText().equals("Edit")){
            cmdBARU.setEnabled(false);
            cmdHAPUS.setEnabled(false);

        }else{
            try {
                StoreData();
                list_all();
            } catch (SQLException ex) {
                Logger.getLogger(frmtodolist.class.getName()).log(Level.SEVERE, null, ex);
            }
            cmdHAPUS.setEnabled(true);
            cmdBARU.setEnabled(true);
        }
    }//GEN-LAST:event_cmdUBAHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmtodolist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmtodolist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmtodolist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmtodolist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            try {
                    new frmtodolist().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frmtodolist.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBNAME;
    private javax.swing.JButton cmdBARU;
    private javax.swing.JButton cmdHAPUS;
    private javax.swing.JButton cmdTUTUP;
    private javax.swing.JButton cmdUBAH;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtb;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel pasphoto;
    private javax.swing.JLabel pasphoto1;
    private javax.swing.JLabel pasphoto2;
    private javax.swing.JLabel pasphoto3;
    private javax.swing.JLabel pasphoto4;
    private javax.swing.JTextField txtCATEGORY;
    private javax.swing.JTextField txtDATE;
    private javax.swing.JTextField txtDESCRIPTION;
    private javax.swing.JTextField txtNAME;
    // End of variables declaration//GEN-END:variables

}
